version: "3"
services:
  fr-web:
    build: .
    ports:
      - "127.0.0.1:5000:80"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
    command: ["gunicorn", "--reload", "--bind=0.0.0.0:80", "app:app"]
  fr-redis:
    image: redis