version: "3"
services:
  fr-web:
    build: .
    ports:
      - "127.0.0.1:5000:80"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
    command: ["gunicorn", "--bind=0.0.0.0:80", "app:app"]
  fr-rq-worker:
    build: .
    volumes:
      - .:/app
    command: ["rq", "worker", "-s", "-u", "redis://fr-redis:6379/0"]
  fr-redis:
    image: redis
